name: qlnh_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  flutter_slidable: ^3.1.0
  socket_io_client: ^2.0.3
  fluttertoast: ^8.2.4
  another_flushbar: ^1.12.30
  fl_chart: ^0.68.0
  collection: ^1.18.0
  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.1.0
  image_picker: ^1.1.2
  flutter_animate: ^4.5.0
  qr_flutter: ^4.1.0
  google_fonts: ^6.2.1
  simple_animations: ^5.0.2

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  intl: ^0.20.2
  webview_flutter: ^4.13.0
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  badges: ^3.1.2
  local_auth: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

